FROM python:3.11-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

RUN mkdir -p logs

CMD ["python", "main.py"]
#CMD ["sh", "-c", "python3 main.py && touch /tmp/done && sleep infinity"]
