FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.collector.txt /app/
RUN pip install --no-cache-dir -r requirements.collector.txt

COPY data_collector.py /app/

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

#CMD ["python", "data_collector.py"]
